name: Bug Report
description: Reporte um erro encontrado no sistema
title: "[Bug] "
labels: []
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reportar um bug! Preencha os campos abaixo para que possamos identificar e corrigir o problema.

  - type: textarea
    id: descricao
    attributes:
      label: Descrição do problema
      description: Resuma claramente o que está acontecendo de errado.
      placeholder: |
        Ex: Ao clicar no botão de login, nada acontece.
    validations:
      required: true

  - type: textarea
    id: reproducao
    attributes:
      label: Como reproduzir
      description: Passo a passo para reproduzir o bug.
      placeholder: |
        1. Vá até a tela de login
        2. Digite email e senha válidos
        3. Clique em "Entrar"
        4. Observe que nada acontece
    validations:
      required: true

  - type: input
    id: ambiente
    attributes:
      label: Ambiente
      description: Em qual ambiente o erro foi encontrado?
      placeholder: |
        Ex: Produção, Homologação, Local...
    validations:
      required: true

  - type: dropdown
    id: severidade
    attributes:
      label: Severidade
      description: Qual o impacto do erro?
      options:
        - Crítico (afeta todos os usuários ou causa falha total)
        - Alto (impede função principal para alguns usuários)
        - Médio (bug perceptível, mas contornável)
        - Baixo (erro visual ou de menor impacto)
    validations:
      required: true

  - type: textarea
    id: imagens
    attributes:
      label: Capturas de tela ou evidências (opcional)
      description: Se possível, anexe prints ou links com vídeos.
      placeholder: |
        Arraste imagens aqui ou cole links (ex: imgur.com, loom.com)
    validations:
      required: false
