name: Setar Work Item como 'Bug'

on:
  issues:
    types: [opened]

jobs:
  setar_workitem_bug:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      contents: read

    steps:
      - name: Verifica se é bug pelo título
        id: checar
        run: |
          if [[ "${{ github.event.issue.title }}" == "[Bug]"* ]]; then
            echo "IS_BUG=true" >> $GITHUB_ENV
          fi

      - name: Obter project-id pelo número do projeto
        if: env.IS_BUG == 'true'
        run: |
          echo "🔎 Buscando project-id..."
          PROJECT_ID=$(gh project list --owner Leo-Fernandes-sh3 --format json \
            | jq -r '.projects[] | select(.number == 5) | .id')

          echo "::notice::PROJECT_ID=$PROJECT_ID"

          if [ -z "$PROJECT_ID" ]; then
            echo "::error::PROJECT_ID não encontrado"
            exit 1
          fi

          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Obter item-id da issue no projeto
        if: env.IS_BUG == 'true'
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          ITEM_ID=$(gh project item-list 5 --owner Leo-Fernandes-sh3 --format json \
            | jq -r --arg num "$ISSUE_NUMBER" '.items[] | select(.content.number == ($num | tonumber)) | .id')

          echo "::notice::ITEM_ID=$ITEM_ID"

          if [ -z "$ITEM_ID" ]; then
            echo "::error::Item da issue não encontrado no projeto"
            exit 1
          fi

          echo "ITEM_ID=$ITEM_ID" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Obter field-id do campo "Work Item"
        if: env.IS_BUG == 'true'
        run: |
          FIELD_ID=$(gh project field-list 5 --owner Leo-Fernandes-sh3 --format json \
            | jq -r '.fields[] | select(.name == "Work Item") | .id')
          echo "FIELD_ID=$FIELD_ID" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Atualizar campo Work Item como 'Bug'
        if: env.IS_BUG == 'true'
        run: |
          gh project item-edit \
            --id "$ITEM_ID" \
            --project-id "$PROJECT_ID" \
            --field-id "$FIELD_ID" \
            --single-select-option-id 40c1efaf
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
