name: Setar Work Item automaticamente

on:
  issues:
    types: [opened]

jobs:
  setar_workitem:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      contents: read

    steps:
      - name: Detectar tipo de Work Item pelo título
        id: checar_tipo
        run: |
          TITLE="${{ github.event.issue.title }}"

          if [[ "$TITLE" == "[Epic]"* ]]; then
            echo "WORKITEM_TYPE=Epic" >> $GITHUB_ENV
            echo "WORKITEM_ID=dfaa6f33" >> $GITHUB_ENV
          elif [[ "$TITLE" == "[Feature]"* ]]; then
            echo "WORKITEM_TYPE=Feature" >> $GITHUB_ENV
            echo "WORKITEM_ID=1c577033" >> $GITHUB_ENV
          elif [[ "$TITLE" == "[User Story]"* ]]; then
            echo "WORKITEM_TYPE=User Story" >> $GITHUB_ENV
            echo "WORKITEM_ID=479d4cd7" >> $GITHUB_ENV
          elif [[ "$TITLE" == "[Bug]"* ]]; then
            echo "WORKITEM_TYPE=Bug" >> $GITHUB_ENV
            echo "WORKITEM_ID=40c1efaf" >> $GITHUB_ENV
          elif [[ "$TITLE" == "[Incident]"* ]]; then
            echo "WORKITEM_TYPE=Incident" >> $GITHUB_ENV
            echo "WORKITEM_ID=16f9a1a3" >> $GITHUB_ENV
          elif [[ "$TITLE" == "[Task]"* ]]; then
            echo "WORKITEM_TYPE=Task" >> $GITHUB_ENV
            echo "WORKITEM_ID=69c61e35" >> $GITHUB_ENV
          fi

      - name: Obter project-id pelo número do projeto
        if: env.WORKITEM_ID
        run: |
          PROJECT_ID=$(gh project list --owner Leo-Fernandes-sh3 --format json \
            | jq -r '.projects[] | select(.number == 5) | .id')

          echo "::notice::PROJECT_ID=$PROJECT_ID"

          if [ -z "$PROJECT_ID" ]; then
            echo "::error::PROJECT_ID não encontrado"
            exit 1
          fi

          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Obter item-id da issue no projeto
        if: env.WORKITEM_ID
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          ITEM_ID=$(gh project item-list 5 --owner Leo-Fernandes-sh3 --format json \
            | jq -r --arg num "$ISSUE_NUMBER" '.items[] | select(.content.number == ($num | tonumber)) | .id')

          echo "::notice::ITEM_ID=$ITEM_ID"

          if [ -z "$ITEM_ID" ]; then
            echo "::error::Item da issue não encontrado no projeto"
            exit 1
          fi

          echo "ITEM_ID=$ITEM_ID" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Obter field-id do campo "Work Item"
        if: env.WORKITEM_ID
        run: |
          FIELD_ID=$(gh project field-list 5 --owner Leo-Fernandes-sh3 --format json \
            | jq -r '.fields[] | select(.name == "Work Item") | .id')
          echo "FIELD_ID=$FIELD_ID" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Atualizar campo Work Item com tipo detectado
        if: env.WORKITEM_ID
        run: |
          echo "::notice::Atribuindo Work Item como $WORKITEM_TYPE"
          gh project item-edit \
            --id "$ITEM_ID" \
            --project-id "$PROJECT_ID" \
            --field-id "$FIELD_ID" \
            --single-select-option-id "$WORKITEM_ID"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          WORKITEM_TYPE: ${{ env.WORKITEM_TYPE }}
          WORKITEM_ID: ${{ env.WORKITEM_ID }}